# Generated by Django 6.1 on 2026-08-16 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'readiness_snapshot',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='progresstracking',
            name='progress_tr_user_id_83e249_idx',
        ),
        migrations.AddField(
            model_name='readinesssnapshot',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.career'),
        ),
        migrations.AddField(
            model_name='readinesssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProgressTracking',
        ),
    ]
