# Generated by Django 6.1 on 2026-08-15 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.URLField(blank=True, default='')),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of extracted skills')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technologies and frameworks')),
                ('experience', models.JSONField(blank=True, default=list, help_text='Work experience extracted from resume')),
                ('education', models.JSONField(blank=True, default=list, help_text='Education details extracted from resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
