services:
  postgres:
    image: postgres:17
    container_name: techlens-postgres
    environment:
      POSTGRES_DB: techlens_db
      POSTGRES_USER: techlens_user
      POSTGRES_PASSWORD: techlens_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: